const apiEndpoints = {

  Currency_List: "https://restcountries.com/v3.1/all?fields=currencies",
  // user api
  Bestays_User_Signup: "/user/auth/signin",
  Bestays_User_OtpVerify: "/user/auth/otp/verify",
  Bestays_User_OtpResend: "/user/auth/otp/resend",
  Bestays_User_GoogleSignIn: "/user/auth/google/signin",
  Bestays_User_AccountSetUp: `user/account/setup/complete/:$userId`,
  Bestays_User_LogOut: "/user/auth/signout",
  Bestays_User_All_Categories: "/user/get-allcategories",
  Bestays_User_All_Homestays: "/user/get-allhomestays",
  Bestays_User_Homestay_Id: "/user/homestay/:$homestayId/:$currency",
  Bestays_User_Homestay_Locations: "/user/get-all-locations",
  Bestays_User_Profile_Update: `/user/auth/update-profile`,
  Bestays_User_Profile_View: `/user/auth/view-profile`,
  Bestays_User_Homestay_Booking: "/user/book/homestay",
  Bestays_User_Get_Valid_Coupons: "/user/get-coupons?:query",
  Bestays_User_Apply_Coupon: "/user/apply-coupon",
  Bestays_User_Latest_Coupon: "/user/get-latestcoupon",
  Bestays_User_Homestay_Booking_Complete: "/user/book/homestay/complete",
  Bestays_User_Homestay_Booking_List: "/user/homestay/my-bookings?:query",
  Bestays_User_Homestay_CheckIn: "/user/homestay/checkin/:$bookingId",
  Bestays_User_Homestay_CheckOut: "/user/homestay/checkout/:$bookingId",
  Bestays_User_Homestay_Cancel: "/user/homestay/cancel/:$bookingId",
  Bestays_User_Homestay_Booking_Status: "/user/homestay/booking/:$homeStayId/status",
  Bestays_User_Homestay_Submit_Review: "/user/submit-review",
  Bestays_User_Homestay_Get_Review: "/user/test/:$homeStayId",
  Bestays_User_Homestay_Download_Receipt: "/user/download-receipt/:$bookingId",

  // admin api
  Bestays_Admin_Signup: "/admin/auth/signup",
  Bestays_Admin_OtpVerify: "/admin/auth/otp/verify",
  Bestays_Admin_Signin: "/admin/auth/signin",
  Bestays_Admin_LogOut: "/admin/auth/logout",
  Bestays_Admin_Otp_Resend: "/admin/auth/otp/resend",
  Bestays_Admin_Category_Add: "/admin/add-category",
  Bestays_Admin_Category_Get_All: "/admin/get-allcategories",
  Bestays_Admin_Category_Toggle: "admin/toggle-category/:$categoryId",
  Bestays_Admin_Category_Edit: "admin/edit-category/:$categoryId",
  Bestays_Admin_Amenities_Add: "/admin/add-amenities",
  Bestays_Admin_Amenities_Get_All: "/admin/get-allamenities",
  Bestays_Admin_Amenities_Toggle: "/admin/toggle-amenity/:$amenityId",
  Bestays_Admin_Amenities_Edit: "/admin/edit-amenity/:$amenityId",
  Bestays_Admin_User_Get_All: "/admin/get-allusers",
  Bestays_Admin_User_Toggle: "/admin/toggle-user/:$userId",
  Bestays_Admin_Add_Homestay: "/admin/add-homestay",
  Bestays_Admin_Get_Homestays: "/admin/get-allhomestays",
  Bestays_Admin_Homestays_Toggle: "/admin/toggle-homestay/:$homestayId",
  Bestays_Admin_Homestays_Edit: "/admin/update-homestay/:$homestayId",
  Bestays_Admin_Add_Coupon: "/admin/add-coupon",
  Bestays_Admin_Coupon_Edit: "/admin/update-coupon/:$id",
  Bestays_Admin_Coupons_Toggle: "/admin/toggle-coupon/:$id",
  Bestays_Admin_Coupons_Get_All: "/admin/get-allcoupons",
  Bestays_Admin_Homestays_Edit: "/admin/update-homestay/:$homestayId",
  Bestays_Admin_Get_All_Bookings: "/admin/get-allbookings",
  Bestays_Admin_Image_Reordering: "/admin/homestay/:$homeStayId/images",
  Bestays_Admin_Monthly_Report: "/admin/month/report",
  Bestays_Admin_Homestay_Wise_Report: "/admin/homestay/report",
  Bestays_Admin_Category_Wise_Report: "/admin/category/report",
  Bestays_Admin_Yearly_Report: "/admin/yearly/report",
  Bestays_Admin_Overall_Report: "/admin/overall/report",
  Bestays_Admin_Add_Restaurent: "/admin/add-restaurent",
  Bestays_Admin_Get_Restaurent: "/admin/get-restaurents",
  Bestays_Admin_Put_Restaurent: "/admin/restaurant/:id",
};

export default apiEndpoints;
